### ISSUE TITLE
Несколько вопросов

### ISSUE THREAD

**Issue by mrkaban** [henrypp/inetops#3]
Здравствуйте, программа очень давно не обновлялась, вы больше не будете её поддерживать? 

Она мне показалась интересной, поэтому добавил её на свой сайт ([ссылка](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%81%D0%B5%D1%82%D1%8C,-%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82/%D0%BF%D1%80%D0%BE%D1%87%D0%B5%D0%B5/inetops-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5-%D1%81%D0%B5%D1%82%D0%B5%D0%B2%D1%8B%D0%B5-%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B8.html)).

**Comment by henrypp** [comment]
Скорей всего нет, эта работа скорее курсовая работа студента (как и все остальные).
